// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnMgmt.Web.Data;

#nullable disable

namespace VulnMgmt.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106233503_AddUserLastLoginDate")]
    partial class AddUserLastLoginDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Host", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DNSName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownIPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownMACAddress")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastScanVulnCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetBIOSName")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("OSVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DNSName");

                    b.HasIndex("NetBIOSName");

                    b.HasIndex("SiteId");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.HostVulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CVE")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExploitEase")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExploitFrameworks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstDiscovered")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExploitable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastObserved")
                        .HasColumnType("TEXT");

                    b.Property<string>("MACAddress")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PluginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemediationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemediationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Repository")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeeAlso")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VulnPublicationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("PluginId");

                    b.HasIndex("RemediationStatus");

                    b.HasIndex("Severity");

                    b.HasIndex("HostId", "PluginId");

                    b.ToTable("HostVulnerabilities");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.ScanImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("HostsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VulnerabilitiesImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VulnerabilitiesUpdated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportDate");

                    b.HasIndex("ImportedById");

                    b.HasIndex("SiteId");

                    b.ToTable("ScanImports");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("POCEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("POCName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("POCPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationName");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWindowsAuth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.AuditLog", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Host", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.Site", "Site")
                        .WithMany("Hosts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.HostVulnerability", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.Host", "Host")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.ScanImport", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.User", "ImportedBy")
                        .WithMany("ScanImports")
                        .HasForeignKey("ImportedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VulnMgmt.Web.Models.Domain.Site", "Site")
                        .WithMany("ScanImports")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedBy");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Host", b =>
                {
                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Site", b =>
                {
                    b.Navigation("Hosts");

                    b.Navigation("ScanImports");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ScanImports");
                });
#pragma warning restore 612, 618
        }
    }
}
