// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnMgmt.Web.Data;

#nullable disable

namespace VulnMgmt.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Host", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DNSName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownIPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownMACAddress")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastScanVulnCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetBIOSName")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("OSVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DNSName");

                    b.HasIndex("NetBIOSName");

                    b.HasIndex("SiteId");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.HostVulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CVE")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExploitEase")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExploitFrameworks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstDiscovered")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExploitable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastObserved")
                        .HasColumnType("TEXT");

                    b.Property<string>("MACAddress")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PluginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemediationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemediationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Repository")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeeAlso")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VulnPublicationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("PluginId");

                    b.HasIndex("RemediationStatus");

                    b.HasIndex("Severity");

                    b.HasIndex("HostId", "PluginId");

                    b.ToTable("HostVulnerabilities");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.ScanImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("HostsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VulnerabilitiesImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VulnerabilitiesUpdated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportDate");

                    b.HasIndex("ImportedById");

                    b.HasIndex("SiteId");

                    b.ToTable("ScanImports");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("POCEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("POCName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("POCPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationName");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigBenchmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StigId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("StigId")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("StigBenchmarks");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigBenchmarkVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BenchmarkDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Release")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StigBenchmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StigBenchmarkId");

                    b.HasIndex("StigBenchmarkId", "Version", "Release")
                        .IsUnique();

                    b.ToTable("StigBenchmarkVersions");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenchmarkVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotAFindingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotApplicableCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotReviewedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkVersionId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HostId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("Status");

                    b.ToTable("StigChecklists");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigChecklistResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChecklistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("FindingDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeverityOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeverityOverrideJustification")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StigRuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("Status");

                    b.HasIndex("StigRuleId");

                    b.HasIndex("ChecklistId", "StigRuleId")
                        .IsUnique();

                    b.ToTable("StigChecklistResults");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenchmarkVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCIs")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discussion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FixText")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyIds")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VulnId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkVersionId");

                    b.HasIndex("RuleId");

                    b.HasIndex("Severity");

                    b.HasIndex("VulnId");

                    b.HasIndex("BenchmarkVersionId", "VulnId")
                        .IsUnique();

                    b.ToTable("StigRules");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWindowsAuth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.AuditLog", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Host", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.Site", "Site")
                        .WithMany("Hosts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.HostVulnerability", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.Host", "Host")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.ScanImport", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.User", "ImportedBy")
                        .WithMany("ScanImports")
                        .HasForeignKey("ImportedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VulnMgmt.Web.Models.Domain.Site", "Site")
                        .WithMany("ScanImports")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedBy");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigBenchmark", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.StigBenchmarkVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigBenchmarkVersion", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.StigBenchmark", "StigBenchmark")
                        .WithMany("Versions")
                        .HasForeignKey("StigBenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StigBenchmark");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigChecklist", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.StigBenchmarkVersion", "BenchmarkVersion")
                        .WithMany("Checklists")
                        .HasForeignKey("BenchmarkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VulnMgmt.Web.Models.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VulnMgmt.Web.Models.Domain.Host", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VulnMgmt.Web.Models.Domain.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BenchmarkVersion");

                    b.Navigation("CreatedBy");

                    b.Navigation("Host");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigChecklistResult", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.StigChecklist", "Checklist")
                        .WithMany("Results")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VulnMgmt.Web.Models.Domain.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VulnMgmt.Web.Models.Domain.StigRule", "StigRule")
                        .WithMany("ChecklistResults")
                        .HasForeignKey("StigRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("ModifiedBy");

                    b.Navigation("StigRule");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigRule", b =>
                {
                    b.HasOne("VulnMgmt.Web.Models.Domain.StigBenchmarkVersion", "BenchmarkVersion")
                        .WithMany("Rules")
                        .HasForeignKey("BenchmarkVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkVersion");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Host", b =>
                {
                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.Site", b =>
                {
                    b.Navigation("Hosts");

                    b.Navigation("ScanImports");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigBenchmark", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigBenchmarkVersion", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigChecklist", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.StigRule", b =>
                {
                    b.Navigation("ChecklistResults");
                });

            modelBuilder.Entity("VulnMgmt.Web.Models.Domain.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ScanImports");
                });
#pragma warning restore 612, 618
        }
    }
}
